- src/app/api/threads-runs/types.ts
- src/modules/chat/assistant-plan/PlanStep.tsx
- src/modules/chat/assistant-plan/utils.ts
Refs: https://github.ibm.com/Incubation/bee-ui/issues/469
> feat(plan): show error in failed step result

- src/modules/tools/ToolCard.tsx
- src/modules/tools/manage/PublicToolModal.tsx
Refs: https://github.ibm.com/Incubation/bee-ui/issues/414
Satisfies the need to include links in public tools description.
> feat(tools): support markdown for description

- src/modules/knowledge/files/KnowledgeFilesUpload.tsx
Refs: https://github.ibm.com/Incubation/bee-ui/issues/628
> fix(knowledge): opening file input window

- src/modules/assistants/builder/AssistantForm.tsx
- src/modules/tools/ToolCard.tsx
- src/modules/tools/manage/UserToolModal.tsx
Refs: https://github.ibm.com/Incubation/bee-ui/issues/592
> feat(tools): auto-enable the user tool created in assistant builder

- .github/workflows/publish-release-image.yml
Moving image registry from Docker Hub to IBM Container Registry
> update image registry to icr

- src/components/EditableSyntaxHighlighter/EditableSyntaxHighlighter.module.scss
- src/components/EditableSyntaxHighlighter/EditableSyntaxHighlighter.tsx
- src/modules/tools/manage/UserToolModal.module.scss
- src/modules/tools/manage/UserToolModal.tsx
Refs: https://github.ibm.com/Incubation/bee-ui/issues/513
> feat(tools): rework user tool modal, add error notification

- src/components/EditableSyntaxHighlighter/EditableSyntaxHighlighter.module.scss
- src/modules/tools/manage/UserToolModal.module.scss
Refs: https://github.ibm.com/Incubation/bee-ui/issues/513#issuecomment-95724006
> feat(tools): update dark mode colors in syntax highlighter

- src/modules/chat/EmptyChatView.tsx
- src/modules/chat/history/FileCount.module.scss
- src/modules/chat/history/FileCount.tsx
- src/modules/chat/history/ThreadItem.module.scss
- src/modules/chat/history/ThreadItem.tsx
- src/modules/chat/history/useThreadFileCount.ts
- src/modules/chat/providers/ChatProvider.tsx
Refs: https://github.ibm.com/Incubation/bee-ui/issues/399
> feat(history): show file count in session history

- src/app/api/schema.d.ts
- src/components/CardsList/CardsList.tsx
- src/components/ConfirmDialog/ConfirmDialog.tsx
- src/components/TablePagination/TablePagination.module.scss
- src/components/TablePagination/TablePagination.tsx
- src/components/TablePagination/usePagination.ts
- src/hooks/useDataResultState.ts
- src/modules/api-keys/ApiKeysHome.module.scss
- src/modules/api-keys/ApiKeysHome.tsx
- src/modules/api-keys/api/queries.ts
- src/modules/api-keys/manage/ApiKeyModal.tsx
- src/modules/chat/providers/ChatProvider.tsx
- src/styles/_theme.scss
- src/styles/global.scss
- src/utils/strings.ts
Refs: https://github.ibm.com/Incubation/bee-ui/issues/616
> feat(api-keys): add paging, owner

- src/components/TextAreaAutoHeight/TextAreaAutoHeight.tsx
- src/modules/assistants/builder/StarterQuestionsTextArea.tsx
- src/modules/chat/layout/InputBar.tsx
- src/utils/formUtils.ts
Refs: https://github.ibm.com/Incubation/bee-ui/issues/643
> feat(chat): populate input with suggestion without submitting it

- src/modules/auth/AcceptToUForm.tsx
Refs: https://github.ibm.com/Incubation/bee-ui/issues/645
> fix(tou): checkbox enabling on scroll

- src/app/api/threads-runs/types.ts
- src/modules/chat/assistant-plan/PlanStep.module.scss
- src/modules/chat/assistant-plan/PlanStep.tsx
- src/modules/chat/assistant-plan/PlanView.module.scss
- src/modules/chat/assistant-plan/PlanWithSources.module.scss
- src/modules/chat/assistant-plan/utils.ts
- src/modules/chat/message/Message.tsx
- src/modules/tools/utils.ts
Refs: https://github.ibm.com/Incubation/bee-ui/issues/557
> feat(plan): remove tool caption, update thinking state with thought

- src/modules/auth/AcceptToUForm.module.scss
Refs: https://github.ibm.com/Incubation/bee-ui/issues/203#issuecomment-96406094
> fix(tou): animation in dark mode

- src/modules/chat/assistant-plan/PlanStep.tsx
- src/modules/tools/utils.ts
Refs: https://github.ibm.com/Incubation/bee-ui/issues/651
> fix(tools): user tools approval

- src/modules/auth/AcceptToUForm.tsx
Refs: https://github.ibm.com/Incubation/bee-ui/issues/645#issuecomment-96478894
> feat(tou): do not block the submit button during animation

- src/components/VersionTag/VersionTag.tsx
- src/layout/shell/NavButton.tsx
- src/modules/auth/SignIn.tsx
[Ref: #10](https://github.com/i-am-bee/internal/issues/10)
> feat(signing): re-enable Google signin for beta release

- src/components/AdminView/AdminView.module.scss
- src/layout/shell/AppShell.module.scss
- src/modules/files/utils.ts
Refs: https://github.ibm.com/Incubation/bee-ui/issues/644
> fix: remove focus styles from main elements

- src/modules/chat/trace/useBuildTraceData.ts
> fix(trace): hide undefined raw prompt

- next.config.mjs
- src/app/layout.tsx
- src/layout/providers/ProgressBarProvider.tsx
- src/layout/providers/ThemeProvider.tsx
- src/middleware.ts
nonce is generated in middleware and then read in a root layout, this means all pages are dynamic
Refs: https://github.com/i-am-bee/internal/issues/28
> feat: add strict csp using nonce without unsafe-inline

- src/app/api/assistants/index.ts
- src/utils/handleApiError.ts
Refs: https://github.com/i-am-bee/internal/issues/48
> fix: deleted thread click causing error

- src/components/UsageLimitModal/UsageLimitModal.tsx
- src/modules/chat/providers/ChatProvider.tsx
- src/modules/knowledge/detail/AddContentModal.tsx
- src/modules/knowledge/files/VectorStoreFilesUploadProvider.tsx
> feat: usage limit modal

- src/app/api/schema.d.ts
- src/app/auth/index.ts
Signed-off-by: Tomas Pilar <tomas.pilar@apoco.com>
> feat(auth): send name explicitly

- src/app/api/authorization/capacity/route.ts
- src/app/auth/signin/page.tsx
Signed-off-by: Tomas Pilar <tomas.pilar@apoco.com>
> feat(capacity): add public endpoint

- src/app/api/authorization/capacity/route.ts
- src/app/auth/signin/page.tsx
- src/components/UsageLimitModal/UsageLimitModal.tsx
- src/modules/apps/builder/ArtifactSharedIframe.tsx
- src/redis.ts
Signed-off-by: Tomas Pilar <tomas.pilar@apoco.com>
> fix(build): remove page export

- src/layout/shell/UserNav.tsx
- src/modules/onboarding/OnboardingIntro.tsx
Closes https://github.com/i-am-bee/internal/issues/47
> feat: change Documentation to Resources

- src/modules/apps/builder/AppBuilder.tsx
- src/modules/apps/builder/ArtifactSharedIframe.tsx
- src/modules/chat/providers/useMessages.ts
- src/modules/chat/types.ts
Implement the "Try to fix this error" button behavior for app builder.
> feat(apps): error reporting and fixing

- src/app/(main)/[projectId]/apps/builder/clone/[artifactId]/page.tsx
- src/modules/apps/builder/AppBuilder.tsx
- src/modules/apps/builder/AppBuilderProvider.tsx
- src/modules/apps/manage/SaveAppModal.tsx
- src/modules/apps/types.ts
- src/modules/assistants/builder/AssistantBuilderProvider.tsx
- src/modules/assistants/types.ts
added "origin" to the uiMetadata of assistant and artifact
Refs: i-am-bee/internal#39
> feat: track app and assistant origins

- src/modules/assistants/tools/ToolNameWithTooltip.tsx
- src/modules/auth/AcceptToUForm.module.scss
- src/modules/tools/hooks/useToolInfo.tsx
Return default icon for system tools without defined one
> fix(tool): fix system tool icon

- src/modules/chat/trace/useBuildTraceData.ts
- src/modules/chat/trace/utils.ts
closes: https://github.com/i-am-bee/bee-observe/issues/14
The streamlit agent does not have iteration, so I load the rawPrompt from all spans in case it does not exist.
> feat(observe): add raw prompt for streamlit agent

- package.json
- patches/next-auth@5.0.0-beta.25.patch
- pnpm-lock.yaml
- src/app/(main)/[projectId]/apps/builder/page.tsx
- src/app/(main)/[projectId]/apps/builder/t/[threadId]/page.tsx
- src/app/(main)/[projectId]/builder/[assistantId]/page.tsx
- src/app/(main)/[projectId]/builder/[assistantId]/thread/[threadId]/page.tsx
- src/app/(main)/[projectId]/chat/[assistantId]/page.tsx
- src/app/(main)/[projectId]/knowledge/[knowledgeId]/page.tsx
- src/app/(main)/[projectId]/thread/[threadId]/page.tsx
- src/app/(main)/layout.tsx
- src/app/api/auth/session/route.ts
- src/app/api/rsc.ts
- src/app/auth/index.ts
- src/app/auth/rsc.tsx
- src/middleware.ts
- src/modules/users/useUpdateUser.ts
- src/pages/api/[...path].ts
- remove `user` removal hack
- correctly propagate new session (cookie) via `/api/auth/session`
- remove unused imports
- bump next-auth and next
> fix(auth): token revalidation and session update

- src/middleware.ts
- src/modules/chat/api/useDeleteMessage.ts
- src/modules/chat/assistant-plan/PlanStep.tsx
- src/modules/chat/assistant-plan/PlanWithSources.tsx
- src/modules/chat/assistant-plan/utils.ts
- src/modules/chat/layout/InputBar.tsx
- src/modules/chat/providers/ChatProvider.tsx
- src/modules/chat/providers/useMessages.ts
> fix(chat): cancel run

- src/modules/chat/layout/InputBar.tsx
- src/modules/knowledge/files/VectorStoreFilesUploadProvider.tsx
> fix(chat): disable submit on pending file upload

- src/modules/apps/builder/AppBuilder.tsx
- src/modules/apps/builder/ArtifactSharedIframe.module.scss
- src/modules/apps/builder/ArtifactSharedIframe.tsx
- src/modules/apps/detail/AppDetail.tsx
Resolves:
- [App use] Use 8 columns wide (min 608px) if possible
> feat: unify sizing of artifact iframe with public site

- src/app/auth/rsc.tsx
> feat: for dummy JWT use username from the API

- src/modules/api-keys/api/useApiKeys.ts
- src/modules/api-keys/api/useCreateApiKey.ts
- src/modules/apps/builder/ArtifactSharedIframe.module.scss
- src/modules/apps/builder/ArtifactSharedIframe.tsx
- fixes: visible app with error until the source code is fully loaded
- updates: loading animation style according to the design
> feat(app-builder): app loading update 
